import React from 'react'
import Navbar from '../../../components/Navbar'
import { useNavigate } from 'react-router-dom'
import OtherFooter from '../../../components/OtherFooter'

export default function TermOfService() {

    const navigate = useNavigate()

    return (
        <div className=' w-full h-screen relative overflow-x-hidden   ' >
            <div className=' w-full top-0 sticky ' >
                <Navbar /> 
            </div>
            <div className=' w-full flex justify-center px-6  ' > 
                <div className=' max-w-[1240px] flex-1 py-9 ' > 
                    <div className=' flex items-center gap-5 ' >  
                        <svg role='button' onClick={()=> navigate(-1)} width="23" height="20" viewBox="0 0 23 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M20.9301 8.66573H4.74465L9.69853 2.8524C9.93017 2.58011 10.0416 2.22907 10.0083 1.8765C9.97508 1.52393 9.79982 1.19872 9.52112 0.972399C9.24242 0.746081 8.88312 0.637198 8.52226 0.669705C8.16139 0.702211 7.82853 0.873443 7.59688 1.14573L0.773355 9.14573C0.727447 9.20936 0.686395 9.27621 0.650531 9.34573C0.650531 9.4124 0.650532 9.4524 0.555002 9.51907C0.493145 9.67194 0.460757 9.83468 0.459473 9.99907C0.460757 10.1635 0.493145 10.3262 0.555002 10.4791C0.555002 10.5457 0.555002 10.5857 0.650531 10.6524C0.686395 10.7219 0.727447 10.7888 0.773355 10.8524L7.59688 18.8524C7.7252 19.0029 7.88588 19.1239 8.0675 19.2069C8.24912 19.2899 8.44722 19.3327 8.64771 19.3324C8.96657 19.333 9.27559 19.2245 9.52112 19.0257C9.65931 18.9138 9.77354 18.7763 9.85726 18.6212C9.94099 18.4661 9.99257 18.2963 10.0091 18.1217C10.0255 17.9471 10.0066 17.771 9.9533 17.6035C9.90002 17.436 9.81344 17.2805 9.69853 17.1457L4.74465 11.3324H20.9301C21.292 11.3324 21.6391 11.1919 21.8951 10.9419C22.151 10.6918 22.2948 10.3527 22.2948 9.99907C22.2948 9.64544 22.151 9.3063 21.8951 9.05626C21.6391 8.80621 21.292 8.66573 20.9301 8.66573Z" fill="black"/>
                        </svg>
                        <p className=' text-[36px] font-bold text-black ' >Legal matters of Ezyswap</p>
                    </div>
                    <div className=' lg:pl-[40px] pt-9 ' >
                        <div role='button' onClick={()=> navigate("/termofservice")} className=' mt-9 flex items-center gap-4 ' >
                            <svg width="20" height="21" viewBox="0 0 20 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M9.8611 1.39057C10.8495 0.731631 12.1336 0.717971 13.1358 1.35573L17.291 3.99994H18.9998C19.5521 3.99994 19.9998 4.44766 19.9998 4.99994V13.9999C19.9998 14.5522 19.5521 14.9999 18.9998 14.9999H17.4801C17.5396 15.9472 17.0933 16.9102 16.1955 17.4489L11.1021 20.505C10.4591 20.8907 9.6609 20.8817 9.0314 20.4974C8.3311 21.1167 7.2531 21.1849 6.47104 20.5704L1.33028 16.5312C0.56387 15.9291 0.37006 14.9003 0.76579 14.0847C0.28248 13.7057 0 13.1254 0 12.5109V5C0 4.44772 0.44772 4 1 4H5.94693L9.8611 1.39057ZM2.17264 12.6452L2.86467 12.0397C4.09488 10.9632 5.96042 11.0698 7.06001 12.2794L9.7622 15.2518C10.6317 16.2083 10.7903 17.6135 10.1579 18.739L15.1665 15.7339C15.4479 15.5651 15.5497 15.2276 15.4448 14.9433L11.0177 8.74551C10.769 8.39736 10.3264 8.24598 9.9166 8.36892L7.43135 9.1145C6.37425 9.4316 5.22838 9.1427 4.44799 8.36235L4.15522 8.06958C3.58721 7.50157 3.44032 6.69318 3.67935 6H2V12.5109L2.17264 12.6452ZM12.0621 3.04306C11.728 2.83047 11.3 2.83502 10.9705 3.05467L5.56943 6.65537L5.8622 6.94814C6.12233 7.20827 6.50429 7.30456 6.85666 7.19885L9.3419 6.45327C10.5713 6.08445 11.8992 6.53859 12.6452 7.58303L16.5144 12.9999H17.9998V5.99994H17.291C16.9106 5.99994 16.5381 5.89148 16.2172 5.68727L12.0621 3.04306ZM4.18168 13.5448L2.56593 14.9586L7.70669 18.9978L8.4106 17.7659C8.6256 17.3897 8.5738 16.9178 8.2823 16.5971L5.58013 13.6247C5.2136 13.2215 4.59175 13.186 4.18168 13.5448Z" fill="black"/>
                            </svg>
                            <p className=' text-[24px] font-medium text-[#2F327A] ' >Acceptance of Terms</p>
                        </div>
                        {/* <div className=' w-full mt-8 font-normal   ' >
                            Welcome to our platform! By accessing or using our services, you agree to comply with the following terms and conditions:
                            <br/><br/>
                            <span className=' text-[#303179] font-bold ' >1. User Responsibilities:</span><br/><br/>
                            - You must be at least 18 years old to use our services.<br/>
                            - You are responsible for maintaining the confidentiality of your account information.<br/>
                            - You agree not to use our platform for any illegal or unauthorized activities.<br/>
                            - You are solely responsible for any content you upload or share on our platform.<br/>
                            <br/><br/>
                            <span className=' text-[#303179] font-bold ' >2. Platform Usage:</span><br/><br/>
                            - Our services are provided on an "as is" and "as available" basis. We do not guarantee uninterrupted access to our platform.<br/>
                            - We reserve the right to modify or discontinue our services at any time without prior notice.<br/>
                            - We may collect and use your personal information in accordance with our Privacy Policy.<br/>
                            <br/><br/>
                            <span className=' text-[#303179] font-bold ' >3. Intellectual Property:</span><br/><br/>
                            - All content on our platform, including logos, text, graphics, and images, is protected by copyright and other intellectual property laws.<br/>
                            - You may not reproduce, distribute, modify, or create derivative works of our content without our prior written consent.<br/>
                            <br/><br/>
                            <span className=' text-[#303179] font-bold ' >4. Limitation of Liability:</span><br/><br/>
                            - We are not liable for any direct, indirect, incidental, or consequential damages arising from your use of our platform.<br/>
                            - We do not guarantee the accuracy, completeness, or reliability of any information on our platform.<br/>
                            <br/><br/>
                            <span className=' text-[#303179] font-bold ' >5. Termination:</span><br/><br/>
                            - We reserve the right to terminate or suspend your access to our services at any time without prior notice.<br/>
                            - You may terminate your account by contacting our support team.<br/>
                            <br/><br/>
                            Please read our full Terms of Service for more detailed information. By using our platform, you acknowledge that you have read, understood, and agreed to these terms. If you do not agree to these terms, please refrain from using our services.
                        </div> */}
                        
                        <div className=' w-full mt-8 font-normal'>
                                Effective Date: @May 27, 2023
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Acceptance of Terms</span><br/><br/>
                                Our Service does not address anyone under the age of 18 (“Children”).<br/><br/>
                                The following Terms and Conditions (these “Terms”) apply to any person that registers or utilises and/or opens an Ezyswap account through Ezyswap Solutions Limited (mobile applications, website, or APIs). These terms constitute a legally binding agreement between you and Ezyswap Solutions Limited, a private limited liability company incorporated under the Laws of the Federal Republic of Nigeria.<br/><br/>
                                For purposes of these Terms, any reference to "We", "Our", "Company", “Ezyswap” "Us" and any similar term refers to the Ezyswap Solutions Limited, and the terms "User", "You" and "Your" refer to a User of our platforms.<br/><br/>
                                By registering for and opening a Ezyswap Account, you unconditionally accept these Terms and agree to be bound by and act in accordance with them. You also acknowledge and agree that you are solely responsible for understanding and complying with all laws, rules, regulations and requirements that may apply to your use of the Ezyswap site and/or your Ezyswap account.‍<br/><br/>
                                Please read these terms carefully before using any Ezyswap service because they affect your legal rights and obligations. By using our service, you agree to these terms and are bound by the same; if you don’t agree with these Terms, don’t use the Service.<br/><br/>
                                The following Terms of Use apply to any person that enrols for and/or opens an Account through www.Ezyswap.com or any associated service, software, API, or participates in limited offers.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Amendment of Terms</span><br/><br/>
                                We may update our terms from time to time. We reserve the right and sole discretion to make changes to these terms at any time. It is your responsibility to check this service periodically for changes. Changes to these terms are effective when they are uploaded to our service.<br/><br/>
                                We will do our best to notify you of any amendments to these Terms that we consider likely to affect your rights and obligations materially. Any such notice will be posted on the Ezyswap website or sent by email to the email address associated with your Ezyswap Account.<br/><br/>
                                Following any amendments, continued use of our service means acceptance and agreement to the changes. If you do not agree with any amendments made to these Terms at any time in future, you must stop using all Ezyswap services with immediate effect. We will send you newsletters, service announcements, and other relevant information as you use our services. You may wish to unsubscribe from our mailing list.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Eligibility</span><br/><br/>
                                By registering to use an Ezyswap Account, you represent and warrant that:<br/><br/>
                                - As an individual, you are at least 18 or the legal age to form a binding contract under applicable laws.<br/>
                                - As an individual, legal person, or other organisation, you have the legal capacity and sufficient authorisations to enter these Terms.<br/>
                                - You will not open, or attempt to open, an Ezyswap Account under any name except your own; or use your Ezyswap Account to carry out transactions on behalf of a third party.<br/>
                                - Suppose you act as an employee or agent of a legal entity and enter into these terms on their behalf. In that case, you represent and warrant that you have all the necessary rights and authorisations to bind such a legal entity.<br/>
                                - Your use of Ezyswap's Services will not violate any laws and regulations applicable to you, including but not limited to anti-money laundering, anti-corruption, and counter-terrorist financing.<br/><br/>
                                By registering to use a Ezyswap Account, you represent and warrant that:<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Using this Service</span><br/><br/>
                                Using this service includes but is not limited to providing information, engaging in digital currency transactions, including conversion of supported digital currency, making submissions and participating in offers. You undertake to use this service only as permitted by law. You agree not to undertake the following:<br/><br/>
                                - Reuse, exploit, and misuse any portion of this service.<br/>
                                - Make any alterations that may interfere with the service provided.<br/>
                                - Use the service to damage the server and impair the use of the service by other users. Use your Account to carry out transactions on behalf of a third party or open an account using the name and details of a third party.<br/>
                                - Obtain unauthorised access to a third party’s account or the Ezyswap database.<br/>
                                - Illegal and prohibited activity as stated in the criminal code of Nigeria and violation of any law, statute or precedent in Nigeria<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Service Availability</span><br/><br/>
                                While we will do everything we can to provide continuous operations, Ezyswap does not provide any warranty in relation to the availability of the Ezyswap Site, API or your Ezyswap Account. Without limiting the generality of the preceding, we do not guarantee continuous access to the Ezyswap Site or your Ezyswap Account and make no representation that the Ezyswap Site, Ezyswap API, your Ezyswap Account and/or any products or services offered therein will be available without interruption; or that there will be no delays, failures, errors, omissions or loss of transmitted information.<br/><br/>
                                Risk Warning and Indemnity<br/><br/>
                                Please note that the risks involved in trading or holding Digital Currencies can be substantial. Digital Currency Services are not currently regulated by the Central Bank of Nigeria or any other regulator. Therefore, carefully consider whether trading or holding Digital Currencies is suitable for your risk appetite.<br/><br/>
                                Before using any of the Ezyswap platforms, you should ensure that you understand the risks involved in Digital Currencies. The digital currency markets can be volatile, and prices can fluctuate significantly, which could result in sudden and significant increases or decreases in the value of your assets.<br/><br/>
                                You should carefully assess whether your financial situation and risk tolerance are suitable for Digital Currencies. You are solely responsible for any decision to send, convert or otherwise hold or deal with Digital Currencies. Ezyswap does not, and will not, offer you any financial advice in connection with your use of or transactions conducted.<br/><br/>
                                You are solely responsible for the decision to use our service to deal with our supported digital currency and accept the risk that underlying software protocols relating to the supported digital currency you store in your Digital Currency Balance may change.<br/><br/>
                                You indemnify Ezyswap, its operating entities or any other affiliates (including their respective directors, members, employees or agents), to the maximum extent permitted by law, against any loss, liability action, cost, claim, damages, proceedings or expense that you may suffer, directly or indirectly, in connection with your Ezyswap account including (without limitation) the loss of digital currencies deposited (whether in whole or in part).<br/><br/>
                                You accordingly hereby waive any claim that you may have against Ezyswap arising therefrom (including in respect of any claim for direct, indirect, consequential or pecuniary damages). You understand and agree that should a counter-party become insolvent or otherwise deliver any deposited amount; this may impact your investment.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Account Information, Verification and Access</span><br/><br/>
                                To use our service, you must open and create your personalised Account. You confirm that all information provided is to open the account is accurate, and you agree to update your information once a change occurs. You will provide security for transactions carried out through your Account by ensuring sufficient local or digital currency in your account or at least the minimum closing amount.<br/><br/>
                                In furtherance of our Anti-Money Laundering & Combating the Financing of Terrorism (AML/CFT) Policy, you agree to provide us with requisite information by filling out the Know Your Client (KYC form). Once the verification procedure has been completed and the KYC form has been filled out, users are granted access to our Service. Kindly visit this link for more information on our AML/CFT policy.<br/><br/>
                                The required information will include but is not limited to the following: name, address, telephone number, e-mail address, date of birth, tax identification number (TIN), valid identification card number, bank verification number and bank account information (such as the name of the bank, the account type, sort code number, and account number).<br/><br/>
                                We may be required to submit additional information on you your business, provide records to regulators or require you to meet with our staff in certain circumstances. This process is enhanced due diligence (“EDD”). We reserve the right to charge you for the EDD, and we will notify you of the same where appropriate. While we verify your identity and carry out the EDD, you agree that there may be delays accessing your account and carrying out transactions. Once the process is complete, your account will run seamlessly.<br/><br/>
                                As part of the Identity Verification and EDD procedures, we are required to retain certain information even after we have closed and suspended your account, or you have terminated your account. See our privacy and AML/CFT policy for more information. To protect your Account, which comprises your balances amongst others, keep your password and pin confidential and secure. You are responsible for any activity carried out using our service. Proceeds realised from the sale of your supported digital currency(s) will be credited to your Balances, less any applicable fees and taxes and interest.<br/><br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Ezyswap reserves the right to, at any time:</span><br/><br/>
                                Restrict or suspend your Ezyswap Account when we, in our sole discretion, consider it necessary to carry out further Identity Verification and/or EDD; or<br/>
                                Terminate your Ezyswap Account if you provide, or we suspect you have provided, false information or refuse to provide the information we require for Identity Verification and/or EDD.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Retention of information</span><br/><br/>
                                Ezyswap is mandated to retain certain information and documentation obtained as part of the Identity Verification and EDD procedures. These requirements apply even when you have terminated your relationship with Ezyswap. We reserve the right to keep such information and documentation for the required period. You accept and agree that information and documentation you provide to Ezyswap may be retained by us, including following the closure of your Ezyswap Account.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Balances</span><br/><br/>
                                The Ezyswap balances services allow you to send the supported fiat currency and/or Digital Currencies to and request, receive and store supported Digital Currencies from third parties according to instructions you provide through the Ezyswap App. Eligible users in certain jurisdictions may send, convert or sell supported Digital Currencies directly from Ezyswap. Ezyswap reserves the right to limit the number of Digital Currencies available for these transactions.<br/><br/>
                                Please note that the Balances is not a deposit account. However, Ezyswap will hold funds received in a designated safekeeping account with a reputable financial institution. E-money held in Balances will not earn any interest. The Supported Digital Currencies by Ezyswap may change from time to time. All transactions must be carried out using the Digital Currencies supported by Ezyswap.<br/><br/>
                                We retain the right to suspend the provision of our services to you:<br/><br/>
                                - If you do not comply with our terms of use, additional police or we discover and are investigating suspected misconduct.<br/>
                                - If you receive any digital currency that digital currency is not an Ezyswap supported Digital Currency.<br/>
                                - If the digital currency is sent to an address associated with your Balances, the address is associated with another digital currency.<br/><br/>
                                After completing the verification procedures, you may convert to supported Digital Currencies directly from Ezyswap. A payment processing fee applies to all conversions. Ezyswap uses third-party payment processors to process any Fiat Currency payment between you and Ezyswap. You will view your balances and your conversion history using the dashboard service, which will show the key account information. This information will include the amount and currency of each conversion, reference to identify the payer or payee, breakdown of fees charged, the rate of exchange, amount after exchange and other details of the exchange.<br/><br/>
                                By using the Ezyswap platform, you acknowledge and agree to the following:<br/><br/>
                                - Ezyswap is not responsible for the operation of the underlying protocols and that Ezyswap makes no guarantee of their functionality, security, or availability; and<br/>
                                - The underlying protocols are subject to sudden changes in operating rules that may materially affect the value, function, and/or even the name of the Digital Currency you store on the Ezyswap platform.<br/><br/>
                                Fiat currency deposited into your Balances is solely for:<br/><br/>
                                - The conversion to supported Digital Currencies,<br/>
                                - Transfer from one balance to another.<br/>
                                - Funding of your debit card<br/>
                                - Withdrawal to an approved bank account.<br/><br/>
                                We may also allow you to purchase specific goods and/or services from selected third parties using your balance in certain countries. You accept and agree that any such purchase will be subject to these Terms. Proceeds from the conversion of supported Digital Currencies will be credited to the Balances, less applicable fees.<br/><br/>
                                You cannot cancel, reverse, or change any transaction marked as complete or pending. If your payment is not successful or if your payment method has insufficient funds, you authorise Ezyswap to cancel the transaction at its sole discretion. You are responsible for maintaining an adequate balance and/or sufficient credit limits to avoid overdraft, insufficient funds, or similar fees charged by your payment provider (i.e., your bank).<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Transaction Instructions</span><br/><br/>
                                Ezyswap processes all transactions according to the instructions received from its users, and we do not guarantee the identity of any user, receiver, requester or other parties. You should verify all transaction information before submitting instructions to Ezyswap. A transaction is not complete while it is pending. Funds associated with transactions in a pending state will be designated accordingly and will not be included in your Ezyswap Account’s available balance or be available to conduct transactions. Ezyswap may charge network fees (miner fees) to process a Digital Currency transaction on your behalf. Ezyswap will calculate the network fee at its discretion, although Ezyswap will always notify you of the network fee at or before the time you authorise the transaction.<br/><br/>
                                Ezyswap has no control over, or liability for, the delivery, quality, safety, legality or any other aspect of any goods or services that you may purchase or sell to or from a third party (including other users of Ezyswap Services). Ezyswap does not own or control the underlying software protocols that govern Digital Currencies' operation supported on our platform. In general, the underlying protocols are open source, and anyone can use, copy, modify, and distribute them.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Ezyswap will process Balances Transactions according to your instructions. You accept and agree that Ezyswap does not:</span><br/><br/>
                                Guarantee the identity of any user, receiver, or another party to a Balances Transaction. You are solely responsible for ensuring all transaction details are correct, and you should carefully verify all transaction information before submitting transaction instructions to Ezyswap.<br/><br/>
                                Have any control over, or any liability concerning, the delivery, quality or any other aspect of any goods or services that you may buy from or sell to any third party. Balances shall not be responsible for and will take no action concerning ensuring that any buyer or seller you transact with using your Balances completes the relevant transaction or has the requisite authority to do so.<br/><br/>
                                You may receive Supported Digital Currencies into your Balances by providing the sender with a receive address generated in your Balances. Your Balances will only be credited with Supported Cryptocurrency sent to a receive address generated through your Balances and associated with that Supported Cryptocurrency.<br/><br/>
                                If you know, suspect, or should reasonably know or suspect that any Local Currency or Digital Currency has been credited to your Balances (or to any bank account) in error, you must immediately notify Balances of the error by submitting a ticket through the Help Centre. You accept and agree that you have no claim or entitlement to any Local Currency or Digital Currency received in error and must immediately return such funds in accordance with the instructions received from Balances.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Fiat deposits</span><br/><br/>
                                Where your identity has been verified (following the Identity Verification requirements), you may deposit Local Currency into your Ezyswap Balances by depositing funds through our payment processors (a “Deposit”). The Ezyswap Balance into which you make a Deposit will be a segregated exclusive account used exclusively to hold and process customer funds. Subject to these Terms, you retain a right to any funds you deposit into the Fiat balance until your funds are used or withdrawn.<br/><br/>
                                Details of the payment method through which you must make the Deposit will be provided to you by Ezyswap, and any such payment method will be held, operated or managed by our payment processors. You accept and agree that any information you provide to Ezyswap may be shared with such a local entity to facilitate your deposits and withdrawals from your Ezyswap Balance. ‍<br/><br/>
                                Due to legal and operational constraints, you must strictly adhere to the following Deposit requirements (the “Deposit Requirements”).<br/><br/>
                                - You may only Deposit Local Currency using a Supported Payment Method compatible with the Payment methods available in your country or region.<br/>
                                - Where you make a deposit using a credit or debit card, you authorise Ezyswap to facilitate the debiting of the funds from your bank account to complete the Deposit.<br/>
                                - You must not use cash or cheques to make a Deposit. Ezyswap reserves the right to refuse any Deposit made by cash or cheque. Should Ezyswap decide, in its sole discretion, to allow a Deposit by cash or cheque on an exceptional basis, Ezyswap will delay the allocation of such Deposit to allow fraud and compliance checks to take place, and a Cash Deposit Penalty may be deducted from it.<br/>
                                - You agree to abide by the Deposit Requirements. You agree and accept that failure to do so may cause a delay in or failure of any Deposit reflecting in your Balances and/or restriction, suspension or termination of your Ezyswap Account.<br/><br/>
                                Deposits may take time to reflect in your Ezyswap Balance due to bank processing times, operational processes, and/or failure by you to adhere to the Deposit Requirements. Under no circumstances will Ezyswap have any liability to you concerning any delay in or failure of a Deposit reflecting in your Ezyswap Balance.<br/><br/>
                                We reserve the right to refuse any transaction if we suspect that such action is in furtherance of illegal and fraudulent activity or that such action will expose Ezyswap to risk. We shall not be liable for any delay or non-completion of a transaction.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Withdrawals</span><br/><br/>
                                Where you have added your bank account details to your Ezyswap Account, you may withdraw funds from your Ezyswap Balance to your bank account or any other account we may support in the future (a “Withdrawal”). Ezyswap will process Withdrawals following your instructions. You are solely responsible for ensuring that any Withdrawal instructions provided to Ezyswap, including the relevant account details, are complete and correct. You accept and agree that under no circumstances will Ezyswap be under any obligation to reverse or amend any Withdrawal.<br/><br/>
                                Ezyswap will make all reasonable efforts to process Withdrawals each business day, following the Deposit and Withdrawal Schedule on the Ezyswap website. You accept and agree that Ezyswap provides no guarantee concerning the Withdrawal processing period.‍<br/><br/>
                                You agree that we have not provided any guarantee in relation to the withdrawal processing period. We reserve the right to refuse any transaction if we suspect that such action is in furtherance of illegal and fraudulent activity or that such action will expose Ezyswap to risk. We shall not be liable for any delay or non-completion of a transaction.<br/><br/><br/>
                                <span className=' text-[#303179] font-bold ' >Account Security</span><br/><br/>
                                Ezyswap takes security very seriously, and we take internal measures to protect your Ezyswap Account are explained on the Security page of the Ezyswap website. However, you are solely responsible for:<br/><br/>
                                - Maintaining adequate security and control over your Ezyswap Account sign-in details, including but not limited to any passwords, personal identification numbers (PINs), API keys, or any other codes associated with your Ezyswap Account.<br/>
                                - Keeping your contact details up to date so that you can receive any notices or alerts we may send to you in relation to security (see Notices).<br/>
                                - Maintaining security and control over the email mailbox, phone number and two-factor authentication applications or devices associated with your Ezyswap Account.<br/><br/>
                                We shall not be liable for any damage or malfunctions caused by viruses, spyware, or other malware that may affect your device or other equipment. We strongly advise the use of reputable virus screening and prevention software to be updated regularly to combat such viruses. Please note the following:<br/>
                                - SMS and email services are vulnerable, and care should be taken when reviewing messages purporting to originate from us.<br/>
                                - Enabling any additional security features available to you, including the activation of two-factor authentication on your Ezyswap account<br/>
                                - We will never seek access to your device or account.<br/>
                                - We will not request your personal identification number (PIN) or other identification code associated with your account.<br/>
                                - Verify the uncertainty and authenticity of any notice of any purported to be made by Ezyswap to your account.<br/><br/>
                                You are to take steps to secure your account details adequately. We shall not be liable for failure to secure your account details, resulting in unauthorised access to your Account and/or results in the tampering of local or digital currency kept in your Balances or any linked bank account(s). You accept that you shall be held responsible for all activities that occur through your account and accept all risks thereof.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Restriction, Suspension, Termination</span><br/><br/>
                                Ezyswap reserves the right to restrict, suspend or terminate your Ezyswap Account where:<br/><br/>
                                - We reasonably suspect that your Ezyswap Account is the subject of an operational or other error, in which case we may suspend access to your account until the error is rectified.<br/>
                                - We reasonably suspect that your Ezyswap Account has been or is being used with any unlawful, fraudulent or Prohibited Activity, or breach of these Terms or our standard Terms of Use;<br/>
                                - We reasonably suspect that you or your Ezyswap Account is or has been associated with or poses a high risk of money laundering, financing of terrorism, fraud, or any other financial crime.<br/>
                                - We reasonably suspect you of taking any action that Ezyswap considers to be a circumvention of Ezyswap’s controls, including but not limited to opening multiple Ezyswap Accounts.<br/>
                                - We reasonably suspect your involvement in any attempt to gain unauthorised access to any Ezyswap Account.<br/>
                                - Your Ezyswap Account is or appears to be the subject of any legal, regulatory or government process and/or we, in our sole discretion, consider there to be a heightened risk of legal or regulatory non-compliance.<br/>
                                - We are compelled to do so by a prima facie valid subpoena, court order, or other binding order of a government or regulatory authority; or<br/><br/>
                                Ezyswap will make all reasonable efforts to notify you of any decision to restrict, suspend or terminate your Ezyswap Account unless we are prevented from doing so by any legal or regulatory process or requirement or where doing so may compromise Ezyswaps security and/or risk management procedures. You accept and agree that Ezyswap is under no obligation to disclose to you the fact of or reason for any decision to restrict, suspend or terminate your Ezyswap Account. Ezyswap shall have no liability to you in connection with the restriction, suspension or termination of your Ezyswap Account.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >You accept that, once your account is closed:</span><br/><br/>
                                - We reserve the right to delete all your account information on our server and the right to retain any information required for legal and operational reasons<br/>
                                - It will not be accessible to you.<br/>
                                - We are under no obligation to notify you of or provide you with any digital currency credited to your Account.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Notice</span><br/><br/>
                                Ezyswap will provide any notices relating to your account or your use of our service on the service or by mailing them to the email address provided by you. You consent to receive all notices electronically.<br/><br/>
                                ‍You have the hardware and software to access, receive and save notices sent to you electronically. All information provided to us is valid and up to date. Any notification sent to the email address provided by you will be deemed received once we send it.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Prohibited Activities</span><br/><br/>
                                You must not use your Ezyswap Account to undertake any of the activities or categories of activity set out in this section (each a “Prohibited Activity”):<br/><br/>
                                - Violation of any laws, statutes, ordinances or regulations. Undertaking, facilitating or supporting criminal activity of any kind, including but not limited to money laundering, terrorist financing, illegal gambling operations or malicious hacking.<br/>
                                - Abusive activity, including but not limited to imposing an unreasonable or disproportionately large load on Ezyswap’s infrastructure or otherwise taking any action that may negatively affect the performance of the Ezyswap Site or Ezyswap’s reputation.<br/>
                                - Attempting to gain unauthorised access to the Ezyswap Site or any Ezyswap Account. Transmitting or uploading any material to the Ezyswap Site that contains viruses, Trojan horses, worms, or any other harmful programmes.<br/>
                                - Transferring your Ezyswap Account access or rights to your Ezyswap Account to a third party, unless as required by law or with Ezyswap's prior consent.<br/>
                                - Fraudulent activity, including but not limited to taking any actions that defraud Ezyswap or a Ezyswap customer, or the provision of any false, inaccurate, or misleading information to Ezyswap.<br/>
                                - Transactions involving items that may help facilitate or enable illegal activity; promote or facilitate hate, violence or racial intolerance; are considered obscene, or maybe stolen goods or the proceeds of crime.<br/>
                                - Intellectual property infringement.<br/>
                                - Sale or purchase of drug, narcotics or controlled substances and paraphernalia, pseudo-Pharmaceuticals: Pharmaceuticals and other products that make health claims that have not been approved or verified by the applicable local and/or national regulatory body.<br/>
                                - Adult Content and Services: Pornography and other obscene materials (including literature, imagery and other media); sites offering any sexually related services such as prostitution, escorts, pay-per-view, adult live chat features.<br/>
                                - Multi-level Marketing: Pyramid schemes, network marketing, and referral marketing programs.<br/>
                                - Unfair, predatory or deceptive practices: Investment opportunities or other services that promise high rewards; Sale or resale of a service without added benefit to the buyer; resale of government offerings without authorisation or added value; sites that we determine in our sole discretion to be unfair, deceptive, or predatory towards consumers.<br/>
                                - High-risk businesses: any businesses that we believe poses an elevated financial risk, legal liability, or violate card network or bank policies.<br/><br/>
                                By opening an Ezyswap Account, you confirm that you will not use your account to undertake any of the above-listed Prohibited Activities or any similar or related activity.<br/><br/>
                                Under no circumstances should you attempt to use your Ezyswap account to store, send, request, or receive currency or Digital Currencies in any form that Ezyswap does not support. Ezyswap assumes no responsibility or liability in connection with any attempt to use Ezyswap Services for a currency that Ezyswap does not support.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Third-party Sites</span><br/><br/>
                                Our Service may contain links to other sites not operated by us. If you click on a third-party link, it may direct you to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for any third-party sites or services' content, privacy policies, or practices. We do not guarantee the identity of any user or third party.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Financial Advice</span><br/><br/>
                                No information provided by this service concerning your account provided through any of our platforms shall constitute financial, investment or other professional advice. You are solely responsible for any decision to deposit, store, convert and send digital currency. Such a decision should consider your risk appetite and financial circumstances.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Taxes</span><br/><br/>
                                You are solely responsible for determining whether and to what extent any taxes apply to any transactions you carry out through your Ezyswap Account and for withholding, collecting, reporting and remitting the correct tax amounts to the appropriate tax authorities.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Disclaimers and Warranties</span><br/><br/>
                                Ezyswap expressly disclaims, and you waive, all warranties of any kind, whether express or implied. We make no representations about the accuracy of the historical digital currency data available on the service. Without limiting the generality of the preceding, your Ezyswap account and any related products or services are offered without any warranty as to merchantability or fitness for any particular purpose.<br/>
                                We will ensure that all requests are processed on time, but we make no warranties regarding the length of time required to complete processing which depends on factors outside our control.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Limitation and Liability</span><br/><br/>
                                In no event shall Ezyswap, its operating entities or any other affiliates (including their respective directors, members, employees or agents) be liable to you for any direct, indirect, special, consequential, exemplary or punitive damages or any other damages of any kind, including but not limited to loss of profit, loss of revenue, loss of business, loss of opportunity, loss of data, whether in contract, tort or otherwise, arising out of or in any way connected with your use of, inability to use, or unavailability of your Ezyswap Account, including without limitation any damages caused by or resulting from any reliance upon any information received from Ezyswap, or that result from mistakes, omissions, interruptions, deletion of files or email, errors, defects, viruses, delays in operation or transmission or any failure of performance, whether or not resulting from a force majeure event, communications failure, theft, destruction or unauthorised access to Ezyswap’s records, programmes or services.<br/>
                                Without limiting the generality of the above, in no event will any liability of Ezyswap, its operating entities, or any other affiliates (including their respective directors, members, employees or agents) arise concerning your use of your Ezyswap Account, exceed (in aggregate) the fees earned by Ezyswap in connection with your use of your Ezyswap Account in the six months immediately preceding the event giving rise to the claim for liability.<br/>
                                ‍The above limitations of liability shall apply to the fullest extent permitted by law in the Federal Republic of Nigeria.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Dispute</span><br/><br/>
                                You and we agree to notify the other party in writing of any claim or dispute that arises in relation to the Ezyswap Site, your Ezyswap Account or these Terms within 30 days of such claim or dispute arising. You and we further agree to attempt informal resolution of any Dispute before bringing a claim in any court or other body.<br/>
                                <br/><br/>
                                This Agreement shall be governed by and construed per the laws of the Federal Republic of Nigeria. Parties agree to submit all disputes, claims or controversies (including non-contractual Disputes, claims or controversies) arising out of or in connection with these Terms, or the breach, termination, enforcement or interpretation thereof (together, Disputes), to the exclusive jurisdiction of the courts of Nigeria.<br/>
                                <br/><br/>
                                <span className=' text-[#303179] font-bold ' >Miscellaneous</span><br/><br/>
                                <span className=' text-[#303179] font-bold ' >Entire Agreement:</span> These Terms constitute the entire agreement and understanding between you and Ezyswap concerning this subject matter and supersede all prior discussions, agreements and understandings of any kind between you and Ezyswap (including but not limited to any prior versions of these Terms).<br/><br/>
                                <span className=' text-[#303179] font-bold ' >Breach:</span> Should you suspect that your Account or any of your details have been compromised or you become aware of any fraud or attempted fraud or any other security incident affecting you and/or Ezyswap. If that happens, you must notify Ezyswap Support immediately by email at support@Ezyswap.com and continue to provide accurate information throughout the Breach. You must take the required steps to reduce and report any Breach. Ezyswap will take into account any failure to provide prompt notification of any Breach.<br/><br/>
                                <span className=' text-[#303179] font-bold ' >Account Inactivity:</span> If you have not accessed your account for a few years and we cannot contact you but hold digital assets on your behalf, we may be required to report and deliver such funds to the relevant authorities as unclaimed money. We reserve the right to deduct a dormancy fee or administrative charges incurred by holding such unclaimed funds.<br/><br/>
                                <span className=' text-[#303179] font-bold ' >Agency:</span> Nothing in this Agreement shall be deemed or shall cause either you or Ezyswap to be treated as the agent of each other**.**<br/><br/>
                                <span className=' text-[#303179] font-bold ' >Invalidity of Terms:</span> If any provision of these terms as may be amended periodically is determined to be invalid or unenforceable, in part or whole under any applicable law, this will not affect the validity of any other provision as stated in these terms.<br/><br/>
                                <span className=' text-[#303179] font-bold ' >Transfer:</span> This agreement is personal to you, and you cannot transfer or assign your rights, interests or obligations to anyone else. We may transfer or assign our rights licenses, interests, and obligations at any time, including as part of a merger, acquisition, or other corporate restructuring, provided that this transfer or assignment does not materially impact the quality of our Services.<br/><br/>
                                <span className=' text-[#303179] font-bold ' >Force Majeure:</span> Ezyswap is not liable for a breach or non-performance of the conditions of these terms to the extent that circumstances beyond the control of Ezyswap cause the breach, its affiliates, employees or agents and for the period those circumstances persist.<br/><br/>
                                <span className=' text-[#303179] font-bold ' >Security:</span> Ezyswap will not be held responsible for any claims over any security.<br/><br/>
                                <span className=' text-[#303179] font-bold ' >Headings:</span> Clause headings in these terms are for convenience only and shall not govern the meaning or interpretation of any provision.<br/><br/>
                                <span className=' text-[#303179] font-bold ' >English Language Controls:</span> These terms and any information that you or we will provide should be in English. The translation of these terms and other documents provided on this service is for your information. In doubt, the English language version of this Agreement and other documents shall prevail.<br/><br/>
                                <span className=' text-[#303179] font-bold ' >Contact Us:</span> We are delighted to always hear from you. legal@Ezyswap.com<br/> 
                        </div>
                    </div>
                </div>
            </div>
            <OtherFooter />
        </div>
    )
}